# Generated by Django 4.2.6 on 2023-10-25 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальное название категории')),
                ('title', models.CharField(max_length=120, verbose_name='Название категории')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение категории')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальное название подкатегории')),
                ('title', models.CharField(max_length=120, verbose_name='Название подкатегории')),
                ('number', models.IntegerField(verbose_name='Номер урока')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальное название продукта')),
                ('title', models.CharField(max_length=120, verbose_name='Название продукта')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория продукта')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory', verbose_name='Подкатегория продукта')),
            ],
        ),
    ]
